[~,~,raw] = xlsread('KnownParams.csv');
knownParams = {};
for i = 1:size(raw,2)
    knownParams{end+1} =raw{2,i};
end

createCMD = ['CREATE TABLE IF NOT EXISTS `transistor_table` (' newline ...
  '`partNumber` varchar(50) NOT NULL,' newline ...
  '`type` tinytext,' newline ...
  '`material` tinytext,' newline ...
  '`dateSubmitted` datetime DEFAULT NULL,' newline ...
  '`submittedBy` tinytext,' newline ...
  '`dataSource` varchar(50) DEFAULT NULL,' newline ...
  '`manufacturer` varchar(50) DEFAULT NULL,' newline ...
  '`errorReported` tinyint(1) DEFAULT NULL,' newline ...
  '`width` decimal(3,3) DEFAULT NULL,' newline ...
  '`length` decimal(3,3) DEFAULT NULL,' newline ...
  '`height` decimal(3,3) DEFAULT NULL,' newline ...
  '`weight` decimal(3,3) DEFAULT NULL,' newline ...
  '`package` varchar(20) DEFAULT NULL,' newline ];
  
 for i = 1:length(knownParams)
    createCMD = [createCMD ...
        '`' knownParams{i} '_min` float DEFAULT NULL,' newline ...
        '`' knownParams{i} '_typ` float DEFAULT NULL,' newline ...
        '`' knownParams{i} '_max` float DEFAULT NULL,' newline ];
 end
  
  
  
 createCMD = [createCMD ... 
  'UNIQUE KEY `partNumber` (`partNumber`)' newline ...
') ENGINE=InnoDB DEFAULT CHARSET=latin1;' newline];